using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Samsung_TV.Commands
{
    public class CommandType
    {
        public enum CommandTypes
        {
            KEY_0,
            KEY_1,
            KEY_2,
            KEY_3,
            KEY_4,
            KEY_5,
            KEY_6,
            KEY_7,
            KEY_8,
            KEY_9,
            KEY_11,
            KEY_12,
            KEY_3SPEED,
            KEY_4_3,
            KEY_16_9,
            KEY_AD,
            KEY_ADDDEL,
            KEY_ALT_MHP,
            KEY_ANGLE,
            KEY_ANTENA,
            KEY_ANYNET,
            KEY_ANYVIEW,
            KEY_APP_LIST,
            KEY_ASPECT,
            KEY_AUTO_ARC_ANTENNA_AIR,
            KEY_AUTO_ARC_ANTENNA_CABLE,
            KEY_AUTO_ARC_ANTENNA_SATELLITE,
            KEY_AUTO_ARC_ANYNET_AUTO_START,
            KEY_AUTO_ARC_ANYNET_MODE_OK,
            KEY_AUTO_ARC_AUTOCOLOR_FAIL,
            KEY_AUTO_ARC_AUTOCOLOR_SUCCESS,
            KEY_AUTO_ARC_CAPTION_ENG,
            KEY_AUTO_ARC_CAPTION_KOR,
            KEY_AUTO_ARC_CAPTION_OFF,
            KEY_AUTO_ARC_CAPTION_ON,
            KEY_AUTO_ARC_C_FORCE_AGING,
            KEY_AUTO_ARC_JACK_IDENT,
            KEY_AUTO_ARC_LNA_OFF,
            KEY_AUTO_ARC_LNA_ON,
            KEY_AUTO_ARC_PIP_CH_CHANGE,
            KEY_AUTO_ARC_PIP_DOUBLE,
            KEY_AUTO_ARC_PIP_LARGE,
            KEY_AUTO_ARC_PIP_LEFT_BOTTOM,
            KEY_AUTO_ARC_PIP_LEFT_TOP,
            KEY_AUTO_ARC_PIP_RIGHT_BOTTOM,
            KEY_AUTO_ARC_PIP_RIGHT_TOP,
            KEY_AUTO_ARC_PIP_SMALL,
            KEY_AUTO_ARC_PIP_SOURCE_CHANGE,
            KEY_AUTO_ARC_PIP_WIDE,
            KEY_AUTO_ARC_RESET,
            KEY_AUTO_ARC_USBJACK_INSPECT,
            KEY_AUTO_FORMAT,
            KEY_AUTO_PROGRAM,
            KEY_AV1,
            KEY_AV2,
            KEY_AV3,
            KEY_BACK_MHP,
            KEY_BOOKMARK,
            KEY_CALLER_ID,
            KEY_CAPTION,
            KEY_CATV_MODE,
            KEY_CHDOWN,
            KEY_CHUP,
            KEY_CH_LIST,
            KEY_CLEAR,
            KEY_CLOCK_DISPLAY,
            KEY_COMPONENT1,
            KEY_COMPONENT2,
            KEY_CONTENTS,
            KEY_CONVERGENCE,
            KEY_CONVERT_AUDIO_MAINSUB,
            KEY_CUSTOM,
            KEY_CYAN,
            KEY_DEVICE_CONNECT,
            KEY_DISC_MENU,
            KEY_DMA,
            KEY_DNET,
            KEY_DNIe,
            KEY_DNSe,
            KEY_DOOR,
            KEY_DOWN,
            KEY_DSS_MODE,
            KEY_DTV,
            KEY_DTV_LINK,
            KEY_DTV_SIGNAL,
            KEY_DVD_MODE,
            KEY_DVI,
            KEY_DVR,
            KEY_DVR_MENU,
            KEY_DYNAMIC,
            KEY_ENTER,
            KEY_ENTERTAINMENT,
            KEY_ESAVING,
            KEY_EXIT,
            KEY_EXT1,
            KEY_EXT2,
            KEY_EXT3,
            KEY_EXT4,
            KEY_EXT5,
            KEY_EXT6,
            KEY_EXT7,
            KEY_EXT8,
            KEY_EXT9,
            KEY_EXT10,
            KEY_EXT11,
            KEY_EXT12,
            KEY_EXT13,
            KEY_EXT14,
            KEY_EXT15,
            KEY_EXT16,
            KEY_EXT17,
            KEY_EXT18,
            KEY_EXT19,
            KEY_EXT20,
            KEY_EXT21,
            KEY_EXT22,
            KEY_EXT23,
            KEY_EXT24,
            KEY_EXT25,
            KEY_EXT26,
            KEY_EXT27,
            KEY_EXT28,
            KEY_EXT29,
            KEY_EXT30,
            KEY_EXT31,
            KEY_EXT32,
            KEY_EXT33,
            KEY_EXT34,
            KEY_EXT35,
            KEY_EXT36,
            KEY_EXT37,
            KEY_EXT38,
            KEY_EXT39,
            KEY_EXT40,
            KEY_EXT41,
            KEY_FACTORY,
            KEY_FAVCH,
            KEY_FF,
            KEY_FF_,
            KEY_FM_RADIO,
            KEY_GAME,
            KEY_GREEN,
            KEY_GUIDE,
            KEY_HDMI,
            KEY_HDMI1,
            KEY_HDMI2,
            KEY_HDMI3,
            KEY_HDMI4,
            KEY_HELP,
            KEY_HOME,
            KEY_ID_INPUT,
            KEY_ID_SETUP,
            KEY_INFO,
            KEY_INSTANT_REPLAY,
            KEY_LEFT,
            KEY_LINK,
            KEY_LIVE,
            KEY_MAGIC_BRIGHT,
            KEY_MAGIC_CHANNEL,
            KEY_MDC,
            KEY_MENU,
            KEY_MIC,
            KEY_MORE,
            KEY_MOVIE1,
            KEY_MS,
            KEY_MTS,
            KEY_MUTE,
            KEY_NINE_SEPERATE,
            KEY_OPEN,
            KEY_PANNEL_CHDOWN,
            KEY_PANNEL_CHUP,
            KEY_PANNEL_ENTER,
            KEY_PANNEL_MENU,
            KEY_PANNEL_POWER,
            KEY_PANNEL_SOURCE,
            KEY_PANNEL_VOLDOW,
            KEY_PANNEL_VOLUP,
            KEY_PANORAMA,
            KEY_PAUSE,
            KEY_PCMODE,
            KEY_PERPECT_FOCUS,
            KEY_PICTURE_SIZE,
            KEY_PIP_CHDOWN,
            KEY_PIP_CHUP,
            KEY_PIP_ONOFF,
            KEY_PIP_SCAN,
            KEY_PIP_SIZE,
            KEY_PIP_SWAP,
            KEY_PLAY,
            KEY_PLUS100,
            KEY_PMODE,
            KEY_POWER,
            KEY_POWEROFF,
            KEY_POWERON,
            KEY_PRECH,
            KEY_PRINT,
            KEY_PROGRAM,
            KEY_QUICK_REPLAY,
            KEY_REC,
            KEY_RED,
            KEY_REPEAT,
            KEY_RESERVED1,
            KEY_RETURN,
            KEY_REWIND,
            KEY_REWIND_,
            KEY_RIGHT,
            KEY_RSS,
            KEY_RSURF,
            KEY_SCALE,
            KEY_SEFFECT,
            KEY_SETUP_CLOCK_TIMER,
            KEY_SLEEP,
            KEY_SOUND_MODE,
            KEY_SOURCE,
            KEY_SRS,
            KEY_STANDARD,
            KEY_STB_MODE,
            KEY_STILL_PICTURE,
            KEY_STOP,
            KEY_SUB_TITLE,
            KEY_SVIDEO1,
            KEY_SVIDEO2,
            KEY_SVIDEO3,
            KEY_TOOLS,
            KEY_TOPMENU,
            KEY_TTX_MIX,
            KEY_TTX_SUBFACE,
            KEY_TURBO,
            KEY_TV,
            KEY_TV_MODE,
            KEY_UP,
            KEY_VCHIP,
            KEY_VCR_MODE,
            KEY_VOLDOWN,
            KEY_VOLUP,
            KEY_WHEEL_LEFT,
            KEY_WHEEL_RIGHT,
            KEY_W_LINK,
            KEY_YELLOW,
            KEY_ZOOM1,
            KEY_ZOOM2,
            KEY_ZOOM_IN,
            KEY_ZOOM_MOVE,
            KEY_ZOOM_OUT,
        }


        public static Dictionary<CommandTypes, string> CommandLookUp = new Dictionary<CommandTypes, string>()
        {
            { CommandTypes.KEY_0,"KEY_0" },
            { CommandTypes.KEY_1,"KEY_1" },
            { CommandTypes.KEY_2,"KEY_2" },
            { CommandTypes.KEY_3,"KEY_3" },
            { CommandTypes.KEY_4,"KEY_4" },
            { CommandTypes.KEY_5,"KEY_5" },
            { CommandTypes.KEY_6,"KEY_6" },
            { CommandTypes.KEY_7,"KEY_7" },
            { CommandTypes.KEY_8,"KEY_8" },
            { CommandTypes.KEY_9,"KEY_9" },
            { CommandTypes.KEY_11,"KEY_11" },
            { CommandTypes.KEY_12,"KEY_12" },
            { CommandTypes.KEY_3SPEED,"KEY_3SPEED" },
            { CommandTypes.KEY_4_3,"KEY_4_3" },
            { CommandTypes.KEY_16_9,"KEY_16_9" },
            { CommandTypes.KEY_AD,"KEY_AD" },
            { CommandTypes.KEY_ADDDEL,"KEY_ADDDEL" },
            { CommandTypes.KEY_ALT_MHP,"KEY_ALT_MHP" },
            { CommandTypes.KEY_ANGLE,"KEY_ANGLE" },
            { CommandTypes.KEY_ANTENA,"KEY_ANTENA" },
            { CommandTypes.KEY_ANYNET,"KEY_ANYNET" },
            { CommandTypes.KEY_ANYVIEW,"KEY_ANYVIEW" },
            { CommandTypes.KEY_APP_LIST,"KEY_APP_LIST" },
            { CommandTypes.KEY_ASPECT,"KEY_ASPECT" },
            { CommandTypes.KEY_AUTO_ARC_ANTENNA_AIR,"KEY_AUTO_ARC_ANTENNA_AIR" },
            { CommandTypes.KEY_AUTO_ARC_ANTENNA_CABLE,"KEY_AUTO_ARC_ANTENNA_CABLE" },
            { CommandTypes.KEY_AUTO_ARC_ANTENNA_SATELLITE,"KEY_AUTO_ARC_ANTENNA_SATELLITE" },
            { CommandTypes.KEY_AUTO_ARC_ANYNET_AUTO_START,"KEY_AUTO_ARC_ANYNET_AUTO_START" },
            { CommandTypes.KEY_AUTO_ARC_ANYNET_MODE_OK,"KEY_AUTO_ARC_ANYNET_MODE_OK" },
            { CommandTypes.KEY_AUTO_ARC_AUTOCOLOR_FAIL,"KEY_AUTO_ARC_AUTOCOLOR_FAIL" },
            { CommandTypes.KEY_AUTO_ARC_AUTOCOLOR_SUCCESS,"KEY_AUTO_ARC_AUTOCOLOR_SUCCESS" },
            { CommandTypes.KEY_AUTO_ARC_CAPTION_ENG,"KEY_AUTO_ARC_CAPTION_ENG" },
            { CommandTypes.KEY_AUTO_ARC_CAPTION_KOR,"KEY_AUTO_ARC_CAPTION_KOR" },
            { CommandTypes.KEY_AUTO_ARC_CAPTION_OFF,"KEY_AUTO_ARC_CAPTION_OFF" },
            { CommandTypes.KEY_AUTO_ARC_CAPTION_ON,"KEY_AUTO_ARC_CAPTION_ON" },
            { CommandTypes.KEY_AUTO_ARC_C_FORCE_AGING,"KEY_AUTO_ARC_C_FORCE_AGING" },
            { CommandTypes.KEY_AUTO_ARC_JACK_IDENT,"KEY_AUTO_ARC_JACK_IDENT" },
            { CommandTypes.KEY_AUTO_ARC_LNA_OFF,"KEY_AUTO_ARC_LNA_OFF" },
            { CommandTypes.KEY_AUTO_ARC_LNA_ON,"KEY_AUTO_ARC_LNA_ON" },
            { CommandTypes.KEY_AUTO_ARC_PIP_CH_CHANGE,"KEY_AUTO_ARC_PIP_CH_CHANGE" },
            { CommandTypes.KEY_AUTO_ARC_PIP_DOUBLE,"KEY_AUTO_ARC_PIP_DOUBLE" },
            { CommandTypes.KEY_AUTO_ARC_PIP_LARGE,"KEY_AUTO_ARC_PIP_LARGE" },
            { CommandTypes.KEY_AUTO_ARC_PIP_LEFT_BOTTOM,"KEY_AUTO_ARC_PIP_LEFT_BOTTOM" },
            { CommandTypes.KEY_AUTO_ARC_PIP_LEFT_TOP,"KEY_AUTO_ARC_PIP_LEFT_TOP" },
            { CommandTypes.KEY_AUTO_ARC_PIP_RIGHT_BOTTOM,"KEY_AUTO_ARC_PIP_RIGHT_BOTTOM" },
            { CommandTypes.KEY_AUTO_ARC_PIP_RIGHT_TOP,"KEY_AUTO_ARC_PIP_RIGHT_TOP" },
            { CommandTypes.KEY_AUTO_ARC_PIP_SMALL,"KEY_AUTO_ARC_PIP_SMALL" },
            { CommandTypes.KEY_AUTO_ARC_PIP_SOURCE_CHANGE,"KEY_AUTO_ARC_PIP_SOURCE_CHANGE" },
            { CommandTypes.KEY_AUTO_ARC_PIP_WIDE,"KEY_AUTO_ARC_PIP_WIDE" },
            { CommandTypes.KEY_AUTO_ARC_RESET,"KEY_AUTO_ARC_RESET" },
            { CommandTypes.KEY_AUTO_ARC_USBJACK_INSPECT,"KEY_AUTO_ARC_USBJACK_INSPECT" },
            { CommandTypes.KEY_AUTO_FORMAT,"KEY_AUTO_FORMAT" },
            { CommandTypes.KEY_AUTO_PROGRAM,"KEY_AUTO_PROGRAM" },
            { CommandTypes.KEY_AV1,"KEY_AV1" },
            { CommandTypes.KEY_AV2,"KEY_AV2" },
            { CommandTypes.KEY_AV3,"KEY_AV3" },
            { CommandTypes.KEY_BACK_MHP,"KEY_BACK_MHP" },
            { CommandTypes.KEY_BOOKMARK,"KEY_BOOKMARK" },
            { CommandTypes.KEY_CALLER_ID,"KEY_CALLER_ID" },
            { CommandTypes.KEY_CAPTION,"KEY_CAPTION" },
            { CommandTypes.KEY_CATV_MODE,"KEY_CATV_MODE" },
            { CommandTypes.KEY_CHDOWN,"KEY_CHDOWN" },
            { CommandTypes.KEY_CHUP,"KEY_CHUP" },
            { CommandTypes.KEY_CH_LIST,"KEY_CH_LIST" },
            { CommandTypes.KEY_CLEAR,"KEY_CLEAR" },
            { CommandTypes.KEY_CLOCK_DISPLAY,"KEY_CLOCK_DISPLAY" },
            { CommandTypes.KEY_COMPONENT1,"KEY_COMPONENT1" },
            { CommandTypes.KEY_COMPONENT2,"KEY_COMPONENT2" },
            { CommandTypes.KEY_CONTENTS,"KEY_CONTENTS" },
            { CommandTypes.KEY_CONVERGENCE,"KEY_CONVERGENCE" },
            { CommandTypes.KEY_CONVERT_AUDIO_MAINSUB,"KEY_CONVERT_AUDIO_MAINSUB" },
            { CommandTypes.KEY_CUSTOM,"KEY_CUSTOM" },
            { CommandTypes.KEY_CYAN,"KEY_CYAN" },
            { CommandTypes.KEY_DEVICE_CONNECT,"KEY_DEVICE_CONNECT" },
            { CommandTypes.KEY_DISC_MENU,"KEY_DISC_MENU" },
            { CommandTypes.KEY_DMA,"KEY_DMA" },
            { CommandTypes.KEY_DNET,"KEY_DNET" },
            { CommandTypes.KEY_DNIe,"KEY_DNIe" },
            { CommandTypes.KEY_DNSe,"KEY_DNSe" },
            { CommandTypes.KEY_DOOR,"KEY_DOOR" },
            { CommandTypes.KEY_DOWN,"KEY_DOWN" },
            { CommandTypes.KEY_DSS_MODE,"KEY_DSS_MODE" },
            { CommandTypes.KEY_DTV,"KEY_DTV" },
            { CommandTypes.KEY_DTV_LINK,"KEY_DTV_LINK" },
            { CommandTypes.KEY_DTV_SIGNAL,"KEY_DTV_SIGNAL" },
            { CommandTypes.KEY_DVD_MODE,"KEY_DVD_MODE" },
            { CommandTypes.KEY_DVI,"KEY_DVI" },
            { CommandTypes.KEY_DVR,"KEY_DVR" },
            { CommandTypes.KEY_DVR_MENU,"KEY_DVR_MENU" },
            { CommandTypes.KEY_DYNAMIC,"KEY_DYNAMIC" },
            { CommandTypes.KEY_ENTER,"KEY_ENTER" },
            { CommandTypes.KEY_ENTERTAINMENT,"KEY_ENTERTAINMENT" },
            { CommandTypes.KEY_ESAVING,"KEY_ESAVING" },
            { CommandTypes.KEY_EXIT,"KEY_EXIT" },
            { CommandTypes.KEY_EXT1,"KEY_EXT1" },
            { CommandTypes.KEY_EXT2,"KEY_EXT2" },
            { CommandTypes.KEY_EXT3,"KEY_EXT3" },
            { CommandTypes.KEY_EXT4,"KEY_EXT4" },
            { CommandTypes.KEY_EXT5,"KEY_EXT5" },
            { CommandTypes.KEY_EXT6,"KEY_EXT6" },
            { CommandTypes.KEY_EXT7,"KEY_EXT7" },
            { CommandTypes.KEY_EXT8,"KEY_EXT8" },
            { CommandTypes.KEY_EXT9,"KEY_EXT9" },
            { CommandTypes.KEY_EXT10,"KEY_EXT10" },
            { CommandTypes.KEY_EXT11,"KEY_EXT11" },
            { CommandTypes.KEY_EXT12,"KEY_EXT12" },
            { CommandTypes.KEY_EXT13,"KEY_EXT13" },
            { CommandTypes.KEY_EXT14,"KEY_EXT14" },
            { CommandTypes.KEY_EXT15,"KEY_EXT15" },
            { CommandTypes.KEY_EXT16,"KEY_EXT16" },
            { CommandTypes.KEY_EXT17,"KEY_EXT17" },
            { CommandTypes.KEY_EXT18,"KEY_EXT18" },
            { CommandTypes.KEY_EXT19,"KEY_EXT19" },
            { CommandTypes.KEY_EXT20,"KEY_EXT20" },
            { CommandTypes.KEY_EXT21,"KEY_EXT21" },
            { CommandTypes.KEY_EXT22,"KEY_EXT22" },
            { CommandTypes.KEY_EXT23,"KEY_EXT23" },
            { CommandTypes.KEY_EXT24,"KEY_EXT24" },
            { CommandTypes.KEY_EXT25,"KEY_EXT25" },
            { CommandTypes.KEY_EXT26,"KEY_EXT26" },
            { CommandTypes.KEY_EXT27,"KEY_EXT27" },
            { CommandTypes.KEY_EXT28,"KEY_EXT28" },
            { CommandTypes.KEY_EXT29,"KEY_EXT29" },
            { CommandTypes.KEY_EXT30,"KEY_EXT30" },
            { CommandTypes.KEY_EXT31,"KEY_EXT31" },
            { CommandTypes.KEY_EXT32,"KEY_EXT32" },
            { CommandTypes.KEY_EXT33,"KEY_EXT33" },
            { CommandTypes.KEY_EXT34,"KEY_EXT34" },
            { CommandTypes.KEY_EXT35,"KEY_EXT35" },
            { CommandTypes.KEY_EXT36,"KEY_EXT36" },
            { CommandTypes.KEY_EXT37,"KEY_EXT37" },
            { CommandTypes.KEY_EXT38,"KEY_EXT38" },
            { CommandTypes.KEY_EXT39,"KEY_EXT39" },
            { CommandTypes.KEY_EXT40,"KEY_EXT40" },
            { CommandTypes.KEY_EXT41,"KEY_EXT41" },
            { CommandTypes.KEY_FACTORY,"KEY_FACTORY" },
            { CommandTypes.KEY_FAVCH,"KEY_FAVCH" },
            { CommandTypes.KEY_FF,"KEY_FF" },
            { CommandTypes.KEY_FF_,"KEY_FF_" },
            { CommandTypes.KEY_FM_RADIO,"KEY_FM_RADIO" },
            { CommandTypes.KEY_GAME,"KEY_GAME" },
            { CommandTypes.KEY_GREEN,"KEY_GREEN" },
            { CommandTypes.KEY_GUIDE,"KEY_GUIDE" },
            { CommandTypes.KEY_HDMI,"KEY_HDMI" },
            { CommandTypes.KEY_HDMI1,"KEY_HDMI1" },
            { CommandTypes.KEY_HDMI2,"KEY_HDMI2" },
            { CommandTypes.KEY_HDMI3,"KEY_HDMI3" },
            { CommandTypes.KEY_HDMI4,"KEY_HDMI4" },
            { CommandTypes.KEY_HELP,"KEY_HELP" },
            { CommandTypes.KEY_HOME,"KEY_HOME" },
            { CommandTypes.KEY_ID_INPUT,"KEY_ID_INPUT" },
            { CommandTypes.KEY_ID_SETUP,"KEY_ID_SETUP" },
            { CommandTypes.KEY_INFO,"KEY_INFO" },
            { CommandTypes.KEY_INSTANT_REPLAY,"KEY_INSTANT_REPLAY" },
            { CommandTypes.KEY_LEFT,"KEY_LEFT" },
            { CommandTypes.KEY_LINK,"KEY_LINK" },
            { CommandTypes.KEY_LIVE,"KEY_LIVE" },
            { CommandTypes.KEY_MAGIC_BRIGHT,"KEY_MAGIC_BRIGHT" },
            { CommandTypes.KEY_MAGIC_CHANNEL,"KEY_MAGIC_CHANNEL" },
            { CommandTypes.KEY_MDC,"KEY_MDC" },
            { CommandTypes.KEY_MENU,"KEY_MENU" },
            { CommandTypes.KEY_MIC,"KEY_MIC" },
            { CommandTypes.KEY_MORE,"KEY_MORE" },
            { CommandTypes.KEY_MOVIE1,"KEY_MOVIE1" },
            { CommandTypes.KEY_MS,"KEY_MS" },
            { CommandTypes.KEY_MTS,"KEY_MTS" },
            { CommandTypes.KEY_MUTE,"KEY_MUTE" },
            { CommandTypes.KEY_NINE_SEPERATE,"KEY_NINE_SEPERATE" },
            { CommandTypes.KEY_OPEN,"KEY_OPEN" },
            { CommandTypes.KEY_PANNEL_CHDOWN,"KEY_PANNEL_CHDOWN" },
            { CommandTypes.KEY_PANNEL_CHUP,"KEY_PANNEL_CHUP" },
            { CommandTypes.KEY_PANNEL_ENTER,"KEY_PANNEL_ENTER" },
            { CommandTypes.KEY_PANNEL_MENU,"KEY_PANNEL_MENU" },
            { CommandTypes.KEY_PANNEL_POWER,"KEY_PANNEL_POWER" },
            { CommandTypes.KEY_PANNEL_SOURCE,"KEY_PANNEL_SOURCE" },
            { CommandTypes.KEY_PANNEL_VOLDOW,"KEY_PANNEL_VOLDOW" },
            { CommandTypes.KEY_PANNEL_VOLUP,"KEY_PANNEL_VOLUP" },
            { CommandTypes.KEY_PANORAMA,"KEY_PANORAMA" },
            { CommandTypes.KEY_PAUSE,"KEY_PAUSE" },
            { CommandTypes.KEY_PCMODE,"KEY_PCMODE" },
            { CommandTypes.KEY_PERPECT_FOCUS,"KEY_PERPECT_FOCUS" },
            { CommandTypes.KEY_PICTURE_SIZE,"KEY_PICTURE_SIZE" },
            { CommandTypes.KEY_PIP_CHDOWN,"KEY_PIP_CHDOWN" },
            { CommandTypes.KEY_PIP_CHUP,"KEY_PIP_CHUP" },
            { CommandTypes.KEY_PIP_ONOFF,"KEY_PIP_ONOFF" },
            { CommandTypes.KEY_PIP_SCAN,"KEY_PIP_SCAN" },
            { CommandTypes.KEY_PIP_SIZE,"KEY_PIP_SIZE" },
            { CommandTypes.KEY_PIP_SWAP,"KEY_PIP_SWAP" },
            { CommandTypes.KEY_PLAY,"KEY_PLAY" },
            { CommandTypes.KEY_PLUS100,"KEY_PLUS100" },
            { CommandTypes.KEY_PMODE,"KEY_PMODE" },
            { CommandTypes.KEY_POWER,"KEY_POWER" },
            { CommandTypes.KEY_POWEROFF,"KEY_POWEROFF" },
            { CommandTypes.KEY_POWERON,"KEY_POWERON" },
            { CommandTypes.KEY_PRECH,"KEY_PRECH" },
            { CommandTypes.KEY_PRINT,"KEY_PRINT" },
            { CommandTypes.KEY_PROGRAM,"KEY_PROGRAM" },
            { CommandTypes.KEY_QUICK_REPLAY,"KEY_QUICK_REPLAY" },
            { CommandTypes.KEY_REC,"KEY_REC" },
            { CommandTypes.KEY_RED,"KEY_RED" },
            { CommandTypes.KEY_REPEAT,"KEY_REPEAT" },
            { CommandTypes.KEY_RESERVED1,"KEY_RESERVED1" },
            { CommandTypes.KEY_RETURN,"KEY_RETURN" },
            { CommandTypes.KEY_REWIND,"KEY_REWIND" },
            { CommandTypes.KEY_REWIND_,"KEY_REWIND_" },
            { CommandTypes.KEY_RIGHT,"KEY_RIGHT" },
            { CommandTypes.KEY_RSS,"KEY_RSS" },
            { CommandTypes.KEY_RSURF,"KEY_RSURF" },
            { CommandTypes.KEY_SCALE,"KEY_SCALE" },
            { CommandTypes.KEY_SEFFECT,"KEY_SEFFECT" },
            { CommandTypes.KEY_SETUP_CLOCK_TIMER,"KEY_SETUP_CLOCK_TIMER" },
            { CommandTypes.KEY_SLEEP,"KEY_SLEEP" },
            { CommandTypes.KEY_SOUND_MODE,"KEY_SOUND_MODE" },
            { CommandTypes.KEY_SOURCE,"KEY_SOURCE" },
            { CommandTypes.KEY_SRS,"KEY_SRS" },
            { CommandTypes.KEY_STANDARD,"KEY_STANDARD" },
            { CommandTypes.KEY_STB_MODE,"KEY_STB_MODE" },
            { CommandTypes.KEY_STILL_PICTURE,"KEY_STILL_PICTURE" },
            { CommandTypes.KEY_STOP,"KEY_STOP" },
            { CommandTypes.KEY_SUB_TITLE,"KEY_SUB_TITLE" },
            { CommandTypes.KEY_SVIDEO1,"KEY_SVIDEO1" },
            { CommandTypes.KEY_SVIDEO2,"KEY_SVIDEO2" },
            { CommandTypes.KEY_SVIDEO3,"KEY_SVIDEO3" },
            { CommandTypes.KEY_TOOLS,"KEY_TOOLS" },
            { CommandTypes.KEY_TOPMENU,"KEY_TOPMENU" },
            { CommandTypes.KEY_TTX_MIX,"KEY_TTX_MIX" },
            { CommandTypes.KEY_TTX_SUBFACE,"KEY_TTX_SUBFACE" },
            { CommandTypes.KEY_TURBO,"KEY_TURBO" },
            { CommandTypes.KEY_TV,"KEY_TV" },
            { CommandTypes.KEY_TV_MODE,"KEY_TV_MODE" },
            { CommandTypes.KEY_UP,"KEY_UP" },
            { CommandTypes.KEY_VCHIP,"KEY_VCHIP" },
            { CommandTypes.KEY_VCR_MODE,"KEY_VCR_MODE" },
            { CommandTypes.KEY_VOLDOWN,"KEY_VOLDOWN" },
            { CommandTypes.KEY_VOLUP,"KEY_VOLUP" },
            { CommandTypes.KEY_WHEEL_LEFT,"KEY_WHEEL_LEFT" },
            { CommandTypes.KEY_WHEEL_RIGHT,"KEY_WHEEL_RIGHT" },
            { CommandTypes.KEY_W_LINK,"KEY_W_LINK" },
            { CommandTypes.KEY_YELLOW,"KEY_YELLOW" },
            { CommandTypes.KEY_ZOOM1,"KEY_ZOOM1" },
            { CommandTypes.KEY_ZOOM2,"KEY_ZOOM2" },
            { CommandTypes.KEY_ZOOM_IN,"KEY_ZOOM_IN" },
            { CommandTypes.KEY_ZOOM_MOVE,"KEY_ZOOM_MOVE" },
            { CommandTypes.KEY_ZOOM_OUT,"KEY_ZOOM_OUT" }
        };
    }
}